export const LANDMARKS = [
  {
    "id": "site_01",
    "code": "01",
    "name": "山仔后派出所",
    "category": "公共安全",
    "plusCode": "4GPW+WG",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 310,
    "y": 405,
    "radius": 40,
    "title": "01 山仔后派出所",
    "description": "山仔后交通與生活樞紐的治安守護站，提供登山旅客急難救助、問路指引與居民在地警政服務的安全據點。",
    "geoLat": 25.13725,
    "geoLon": 121.54625
  },
  {
    "id": "site_02",
    "code": "02",
    "name": "陽明山麥當勞",
    "category": "生活餐飲",
    "plusCode": "4GPW+RC",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 300,
    "y": 445,
    "radius": 40,
    "title": "02 陽明山麥當勞",
    "description": "陪伴文化大學師生與遊客近 37 年的經典地標，是無數人上山約見面集合、吃早餐吹冷氣與等公車的共同青春回憶。",
    "geoLat": 25.137,
    "geoLon": 121.546
  },
  {
    "id": "site_03",
    "code": "03",
    "name": "7-ELEVEN 陽明山門市",
    "category": "生活機能",
    "plusCode": "4GPW+QH",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 410,
    "y": 425,
    "radius": 40,
    "title": "03 7-ELEVEN 陽明山門市",
    "description": "山仔后最熱鬧的 24 小時生活補給站，無論是上山賞花、爬山健行或文大學生深夜消夜，都能隨時採買熱食、零食與日常用品。",
    "geoLat": 25.13687,
    "geoLon": 121.54638
  },
  {
    "id": "site_04",
    "code": "04",
    "name": "山仔后公園",
    "category": "公共綠地",
    "plusCode": "4GPW+V7",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 230,
    "y": 315,
    "radius": 40,
    "title": "04 山仔后公園",
    "description": "隱身在熱鬧街道旁的社區小綠洲，設有林蔭涼亭與長椅，供附近居民晨昏散步、鄰里聊天歇腳與親子戶外活動。",
    "geoLat": 25.13712,
    "geoLon": 121.54563
  },
  {
    "id": "site_05",
    "code": "05",
    "name": "陽明里辦公處 (區民活動中心)",
    "category": "社區服務",
    "plusCode": "4GPW+5W",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 315,
    "y": 295,
    "radius": 40,
    "title": "05 陽明里辦公處 (區民活動中心)",
    "description": "陽明里的在地生活與行政核心，舉辦長青講座、里民聚會與各項公共活動，也是走訪完全里 30 處地標領取榮譽里民證的地方。",
    "geoLat": 25.13537,
    "geoLon": 121.54725
  },
  {
    "id": "site_06",
    "code": "06",
    "name": "台灣中油陽明山加油站",
    "category": "交通補給",
    "plusCode": "4GPW+68",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 328,
    "y": 500,
    "radius": 40,
    "title": "06 台灣中油陽明山加油站",
    "description": "陽明山上極少數的加油補給站，開車或騎車上山賞花、追雪、前往擎天崗或竹子湖前，必定停靠把油箱加滿的地方。",
    "geoLat": 25.1355,
    "geoLon": 121.54575
  },
  {
    "id": "site_07",
    "code": "07",
    "name": "豆留森林 (CAMA)",
    "category": "文化餐飲",
    "plusCode": "4GQW+7M",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 376,
    "y": 168,
    "radius": 40,
    "title": "07 豆留森林 (CAMA)",
    "description": "結合昭和日式老官舍與六百坪幽靜竹林的景觀咖啡旗艦店，讓人置身和風庭院中享用精品手沖咖啡、烘豆體驗與早午餐。",
    "geoLat": 25.13812,
    "geoLon": 121.54663
  },
  {
    "id": "site_08",
    "code": "08",
    "name": "白房子 Yang Ming Cafe",
    "category": "歷史餐飲",
    "plusCode": "4GQW+2C",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 265,
    "y": 188,
    "radius": 40,
    "title": "08 白房子 Yang Ming Cafe",
    "description": "美軍眷舍老洋房改建的純白歐風咖啡館，提供精緻排餐、現烤手工麵包與手沖咖啡，適合朋友聚會、約會與享受悠閒午後。",
    "geoLat": 25.13918,
    "geoLon": 121.5462
  },
  {
    "id": "site_09",
    "code": "09",
    "name": "彩虹谷故事館 (F206)",
    "category": "文史故事",
    "plusCode": "4GPX+82",
    "district": "east",
    "districtName": "東區・愛富美軍宿舍群",
    "x": 230,
    "y": 250,
    "radius": 35,
    "title": "09 彩虹谷故事館 (F206)",
    "description": "座落於愛富三街南側、山仔后美軍眷舍 F 區核心腹地的代表性美式眷舍！門牌代號 F206，完整保留 1950 年代駐台美軍眷屬居住的白木雨淋板雙坡平房、紅磚壁爐大煙囪與開闊庭院。致力於記錄冷戰美軍生活記憶與老屋修復歷史，庭園常能遠眺陽明山世界級的壯麗彩虹，是山仔后文史聚落極具溫度的故事館舍。",
    "geoLat": 25.1383,
    "geoLon": 121.5451
  },
  {
    "id": "site_10",
    "code": "10",
    "name": "美軍宿舍群 (C 區建業路段)",
    "category": "文創聚落",
    "plusCode": "4GPX+RH",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 205,
    "y": 135,
    "radius": 40,
    "title": "10 美軍宿舍群 (C 區建業路段)",
    "description": "全台保存最完整的美式冷戰官兵聚落，兩側有著大煙囪、寬廣草坪與美式平房，是散步拍照、感受美式鄉村街區氛圍的文創漫遊區。",
    "geoLat": 25.137,
    "geoLon": 121.54888
  },
  {
    "id": "site_11",
    "code": "11",
    "name": "雀客藏居陽明山溫泉飯店",
    "category": "溫泉名宿",
    "plusCode": "5G2W+27",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 500,
    "y": 145,
    "radius": 40,
    "title": "11 雀客藏居陽明山溫泉飯店",
    "description": "草山知名的山中溫泉渡假飯店，提供天然純淨的白磺溫泉泡湯、山景客房與中西式美饌，供旅客遠離塵囂放鬆身心。",
    "geoLat": 25.15,
    "geoLon": 121.54563
  },
  {
    "id": "site_12",
    "code": "12",
    "name": "陽明山錫安堂",
    "category": "宗教聖所",
    "plusCode": "4GXX+QV",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 620,
    "y": 195,
    "radius": 40,
    "title": "12 陽明山錫安堂",
    "description": "隱身在山林綠意中的寧靜純白教堂，為在地居民與大學生提供主日崇拜、心靈團契與安靜沉澱心靈的信仰避風港。",
    "geoLat": 25.14937,
    "geoLon": 121.54962
  },
  {
    "id": "site_13",
    "code": "13",
    "name": "草山御賓館 (市定古蹟)",
    "category": "市定古蹟",
    "plusCode": "5H22+99",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 375,
    "y": 75,
    "radius": 40,
    "title": "13 草山御賓館 (市定古蹟)",
    "description": "日治時期為接待裕仁皇太子所建的和洋風官邸，後為孫科院長寓所，是陽明山極具代表性的市定古蹟，讓人近距離見證草山近百年政局文史風雲。",
    "geoLat": 25.15087,
    "geoLon": 121.55088
  },
  {
    "id": "site_14",
    "code": "14",
    "name": "中國文化大學",
    "category": "大專學園",
    "plusCode": "4GPQ+JP",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 100,
    "y": 345,
    "radius": 40,
    "title": "14 中國文化大學",
    "description": "座落在海拔 400 公尺華岡之巔的高等學府，擁有全台最雄偉的中國宮殿式校舍群，也是情侶與遊客看夜景、俯瞰整個大台北盆地景緻的勝地。",
    "geoLat": 25.1365,
    "geoLon": 121.53925
  },
  {
    "id": "site_15",
    "code": "15",
    "name": "亞尼克夢想村",
    "category": "美式甜點",
    "plusCode": "4GPV+JF",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 105,
    "y": 420,
    "radius": 40,
    "title": "15 亞尼克夢想村",
    "description": "由美軍老眷舍改造的超人氣美式烘焙甜點坊，專賣各式招牌現烤派塔、生乳捲與野餐點心，能坐在戶外庭院大樹下享受美式鄉村午茶。",
    "geoLat": 25.1365,
    "geoLon": 121.54363
  },
  {
    "id": "site_16",
    "code": "16",
    "name": "The Cafe By 想 陽明山",
    "category": "文化餐飲",
    "plusCode": "4GPV+FV",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 105,
    "y": 560,
    "radius": 40,
    "title": "16 The Cafe By 想 陽明山",
    "description": "群山環抱中的亮黃色歐風木屋景觀餐廳，擁有落羽松庭園與水池造景，提供義大利麵、早午餐與鬆餅，是拍照打卡與放鬆聚餐的好去處。",
    "geoLat": 25.13612,
    "geoLon": 121.54462
  },
  {
    "id": "site_17",
    "code": "17",
    "name": "陽明山星巴克 (草山門市)",
    "category": "文創名店",
    "plusCode": "4GPV+F5",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 215,
    "y": 515,
    "radius": 40,
    "title": "17 陽明山星巴克 (草山門市)",
    "description": "改建自美軍眷舍的純白木屋咖啡館，完整保留復古紅磚大壁爐與戶外草地櫻花樹，讓人坐在老房子裡喝咖啡、感受美式度假風情。",
    "geoLat": 25.13612,
    "geoLon": 121.54288
  },
  {
    "id": "site_18",
    "code": "18",
    "name": "美軍俱樂部 (BRICK YARD 33 1/3)",
    "category": "歷史餐飲",
    "plusCode": "4GPV+69",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 350,
    "y": 600,
    "radius": 40,
    "title": "18 美軍俱樂部 (BRICK YARD 33 1/3)",
    "description": "原美軍眷屬聯誼俱樂部（草山俱樂部 Club 63）改建之近千坪文創休閒聚落！保留 1950 年代美式紅磚老斜頂、雙紅磚煙囪與開闊人字木屋架，室外前泳池改建為水光瀲灩的景觀無邊際水池露台，池中央設有下沉式白色沙發卡座。園區內矗立著吸睛的巨大黑膠唱片裝置藝術，典藏上萬張珍稀西洋黑膠唱片，濃厚的黑膠爵士音樂與炭烤牛排香氣，重現冷戰美軍駐台的黃金歲月。",
    "geoLat": 25.1355,
    "geoLon": 121.54338
  },
  {
    "id": "site_19",
    "code": "19",
    "name": "陽明山美國渡假村",
    "category": "美式別墅",
    "plusCode": "4GPR+CM",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 175,
    "y": 620,
    "radius": 40,
    "title": "19 陽明山美國渡假村",
    "description": "保留高階軍官眷舍規格的獨棟包棟式渡假園區，擁有獨立大院子、綠意草坪、戶外鞦韆與烤肉設備，適合親友家庭體驗道地美式郊區生活。",
    "geoLat": 25.136,
    "geoLon": 121.54163
  },
  {
    "id": "site_20",
    "code": "20",
    "name": "臺北市立陽明教養院",
    "category": "社福公義",
    "plusCode": "4GPR+53",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 80,
    "y": 705,
    "radius": 40,
    "title": "20 臺北市立陽明教養院",
    "description": "深耕山林間的公立身心障礙全人照護家園，提供中重度心智障礙學員溫暖專業的生活照料、技能陶冶與社區關懷服務。",
    "geoLat": 25.13537,
    "geoLon": 121.54013
  },
  {
    "id": "site_21",
    "code": "21",
    "name": "屋頂上餐廳 (The Top)",
    "category": "夜景地標",
    "plusCode": "4GMQ+VM",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 125,
    "y": 825,
    "radius": 40,
    "title": "21 屋頂上餐廳 (The Top)",
    "description": "全台灣最負盛名、最具代表性的後山百萬夜景景觀餐廳！坐落於文化大學體育館後方的陡峭懸崖邊，依山勢層層構築出四層梯田式柚木觀景大甲板。純白浪漫的峇里島發光帳篷包廂（Cabanas）、Tiffany 藍鏡面無邊際天際水池與崖邊半圓形白色沙發，居高臨下將整座大台北盆地、淡水河與台北 101 的燦爛萬家燈火盡收眼底，是情侶約會與旅人朝聖的夜景第一仙境。",
    "geoLat": 25.13462,
    "geoLon": 121.53913
  },
  {
    "id": "site_22",
    "code": "22",
    "name": "華岡藝校",
    "category": "藝術學園",
    "plusCode": "4GPX+RH",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 555,
    "y": 285,
    "radius": 40,
    "title": "22 華岡藝校",
    "description": "台灣歷史悠久的表演藝術名校，培養無數知名歌手、演員與舞者，走在校門周邊常能聽見學子練琴、排戲與練習歌唱的藝術氛圍。",
    "geoLat": 25.137,
    "geoLon": 121.54888
  },
  {
    "id": "site_23",
    "code": "23",
    "name": "台北歐洲學校 (陽明校區)",
    "category": "國際教育",
    "plusCode": "4GPX+MJ",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 590,
    "y": 360,
    "radius": 40,
    "title": "23 台北歐洲學校 (陽明校區)",
    "description": "匯聚英、法、德跨國教育的小學部校區，美麗的歐風紅瓦斜頂校舍融入草山大自然，為駐台外籍人士與各國學子打造國際化的學習環境。",
    "geoLat": 25.13662,
    "geoLon": 121.549
  },
  {
    "id": "site_24",
    "code": "24",
    "name": "草山猛禽中心",
    "category": "自然生態",
    "plusCode": "4GPX+PJ",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 585,
    "y": 495,
    "radius": 40,
    "title": "24 草山猛禽中心",
    "description": "推廣台灣猛禽保育與救傷的自然教育中心，能認識大冠鷲、鳳頭蒼鷹等在陽明山盤旋的空中霸主，並提供生態講座與望遠鏡觀鳥體驗。",
    "geoLat": 25.13675,
    "geoLon": 121.549
  },
  {
    "id": "site_25",
    "code": "25",
    "name": "YMS onefifteen 初衣食午",
    "category": "時尚選品",
    "plusCode": "4GPX+77",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 565,
    "y": 615,
    "radius": 40,
    "title": "25 YMS onefifteen 初衣食午",
    "description": "讓都市人上山放慢步調、結合美食、藝術、住宿與自然美學的高檔美軍宿舍改建聚落。",
    "geoLat": 25.13562,
    "geoLon": 121.54813
  },
  {
    "id": "site_26",
    "code": "26",
    "name": "花卉試驗中心",
    "category": "自然生態",
    "plusCode": "4GPW+33",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 225,
    "y": 755,
    "radius": 40,
    "title": "26 花卉試驗中心",
    "description": "花卉試驗中心以茶花、杜鵑等花卉培育與展示聞名。遊戲加入密集花圃、茶花灌木、球根花卉展示與花架，將不同花季的色彩集中呈現，方便欣賞；配置為風格化園藝場景。",
    "geoLat": 25.13512,
    "geoLon": 121.54513,
    "sourceUrl": "https://pkl.gov.taipei/News_Content.aspx?n=43E05059FCC72525&s=DD94057B11E5812D"
  },
  {
    "id": "site_27",
    "code": "27",
    "name": "陽明福德宮",
    "category": "民間信仰",
    "plusCode": "4GPW+26",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 345,
    "y": 725,
    "radius": 40,
    "title": "27 陽明福德宮",
    "description": "花卉試驗中心對面的百年土地公廟，是在地里民出入保平安、農作生意興隆的精神寄託，登山客與過路人也常在此停步參拜祈福。",
    "geoLat": 25.135,
    "geoLon": 121.5455
  },
  {
    "id": "site_28",
    "code": "28",
    "name": "臺北市立格致國民中學",
    "category": "初級教育",
    "plusCode": "4GJW+WW",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 350,
    "y": 860,
    "radius": 40,
    "title": "28 臺北市立格致國民中學",
    "description": "隱身在山林綠蔭間的森林生態國中，校園擁有極高的綠覆率與遠眺台北視野，為山仔后在地子弟提供自然健康的求學成長環境。",
    "geoLat": 25.13225,
    "geoLon": 121.54725
  },
  {
    "id": "site_29",
    "code": "29",
    "name": "納美花園 (Navi Garden)",
    "category": "休閒莊園",
    "plusCode": "4GQ2+3M",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 530,
    "y": 760,
    "radius": 40,
    "title": "29 納美花園 (Navi Garden)",
    "description": "佔地六千坪的世外桃源休閒莊園，擁有遼闊的碧綠大草皮、生態池塘與林蔭落葉步道，專門提供浪漫的戶外森林系婚禮、草地野餐與聚會空間。",
    "geoLat": 25.1385,
    "geoLon": 121.554
  },
  {
    "id": "site_30",
    "code": "30",
    "name": "下竹林福德宮",
    "category": "民間信仰",
    "plusCode": "4GJW+7F",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 560,
    "y": 890,
    "radius": 40,
    "title": "30 下竹林福德宮",
    "description": "由市區沿仰德大道進入陽明山的第一道守護小廟，石造古祠隱身於幽靜竹林與老樹旁，百年來默默守護每位登山健行者與歸鄉居民。",
    "geoLat": 25.13062,
    "geoLon": 121.54613
  },
  {
    "id": "site_31",
    "code": "31",
    "name": "臺灣銀行行員訓練所",
    "category": "教育研習",
    "plusCode": "4GQ2+4G",
    "district": "center",
    "districtName": "中區・山仔后核心生活",
    "x": 605,
    "y": 420,
    "radius": 45,
    "title": "31 臺灣銀行行員訓練所",
    "description": "培育國家金融人才的深造基地，坐落於和平路林蔭之中，前身與美軍宿舍群歷史緊密相連，莊嚴大器的現代化教育研習園區。",
    "geoLat": 25.13891,
    "geoLon": 121.54729
  },
  {
    "id": "site_32",
    "code": "32",
    "name": "吉佳咖啡 (山上店)",
    "category": "在地咖啡",
    "plusCode": "4GQ2+27",
    "district": "center",
    "districtName": "中區・山仔后核心生活",
    "x": 480,
    "y": 390,
    "radius": 40,
    "title": "32 吉佳咖啡 (山上店)",
    "description": "隱身菁山路上的陽明山傳奇自烘咖啡名店，標榜新鮮手工烘焙咖啡豆與傳統虹吸式手沖，店內濃郁咖啡香瀰漫，是文大師生與登山熟客的靈魂驛站。",
    "geoLat": 25.13788,
    "geoLon": 121.54712
  },
  {
    "id": "site_33",
    "code": "33",
    "name": "真愛桃花源 庭園餐廳",
    "category": "景觀婚紗",
    "plusCode": "4GQW+73",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 220,
    "y": 340,
    "radius": 45,
    "title": "33 真愛桃花源 庭園餐廳",
    "description": "佔地七千坪的陽明山知名夢幻婚紗攝影基地與庭園景觀餐廳，依山傍水擁有白色哥德式教堂、彩虹風車、落羽松林與浪漫鏡面湖泊。",
    "geoLat": 25.13815,
    "geoLon": 121.54267
  },
  {
    "id": "site_34",
    "code": "34",
    "name": "臺北市教師研習中心",
    "category": "教育文化",
    "plusCode": "4GQ3+4P",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 620,
    "y": 160,
    "radius": 45,
    "title": "34 臺北市教師研習中心",
    "description": "前身為日治昭和時代 1929 年興建之「草山眾樂園」（草山公共浴場），現為市定古蹟。保有日洋折衷溫泉會館風貌，黑瓦大斜頂與草山綠蔭庭園相映，位於陽明路一段與建國街旁，隔磺溪與草山御賓館相對。",
    "geoLat": 25.15024,
    "geoLon": 121.54955
  },
  {
    "id": "site_35",
    "code": "35",
    "name": "林洋港故居 (前美軍總司令官邸)",
    "category": "歷史官舍",
    "plusCode": "4GQW+27",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 265,
    "y": 230,
    "radius": 45,
    "title": "35 林洋港故居 (前美軍總司令官邸)",
    "description": "愛富二街1號，為冷戰時期美軍駐台協防司令部最高長官之總司令官邸，後為前司法院長林洋港寓所。擁有將官級寬闊美式南方鄉村大木屋、紅磚煙囪與百年老樹大庭院。",
    "geoLat": 25.13868,
    "geoLon": 121.5462
  },
  {
    "id": "site_36",
    "code": "36",
    "name": "文化大學學生美食街 (牛肉拌麵)",
    "category": "生活餐飲",
    "plusCode": "4GPR+XJ",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 165,
    "y": 335,
    "radius": 40,
    "title": "36 文化大學學生美食街 (牛肉拌麵)",
    "description": "位於文化大學校區旁的光華路26巷，是無數文化大學師生與校友最難忘的青春美食記憶！傳奇名店「牛肉乾拌麵」鋪滿厚切牛肉片與整碗任舀的大蒜蒜泥，搭配熱騰騰免費暢飲的濃郁大骨牛肉清湯，與隔壁的感恩麵店一同構築起華岡校園旁最熱鬧的人間煙火氣。",
    "geoLat": 25.13744,
    "geoLon": 121.54164
  },
  {
    "id": "site_37",
    "code": "37",
    "name": "文化大學郵局 (華岡大典館)",
    "category": "生活機能",
    "plusCode": "4GPR+QW",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 130,
    "y": 375,
    "radius": 40,
    "title": "37 文化大學郵局 (華岡大典館)",
    "description": "位於中國文化大學校園核心的大典館一樓（華岡路55號），為陽明里與華岡生活圈唯一的實體郵局（臺北125支局）。數十年來承載全校師生與周邊居民的信件包裹收發、儲蓄匯款與家書寄送，門前標誌性的一紅一綠雙色郵筒與綠色郵政機車，是華岡校園最溫暖的經典風景。",
    "geoLat": 25.13685,
    "geoLon": 121.53913
  },
  {
    "id": "site_38",
    "code": "38",
    "name": "比夢烘焙坊 (The Cafe' By 想 陽明山)",
    "category": "文化餐飲",
    "plusCode": "4GQW+26",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 230,
    "y": 250,
    "radius": 40,
    "title": "38 比夢烘焙坊 (The Cafe' By 想 陽明山)",
    "description": "座落於愛富一街的美軍宿舍歐風紅磚平房，是陽明山極具盛名的人氣手作烘焙坊。擁有落地採光玻璃屋、夢幻落羽松大庭院與現烤出爐的生吐司、法式肉桂捲香氣，吸引無數遊客在此享受陽明山悠閒的早午餐與午後陽光。",
    "geoLat": 25.13848,
    "geoLon": 121.54555
  },
  {
    "id": "site_39",
    "code": "39",
    "name": "康迎鼎 陽明山店 (小籠包與大蒸籠)",
    "category": "歷史餐飲",
    "plusCode": "4GPX+26",
    "district": "east",
    "districtName": "東區・愛富美軍宿舍群",
    "x": 310,
    "y": 280,
    "radius": 40,
    "title": "39 康迎鼎 陽明山店 (小籠包與大蒸籠)",
    "description": "座落於愛富二街2巷與愛富二街交會處、白房子隔壁的美軍老宿舍中式點心名店！保留美式老眷舍白牆紅柱風貌，最著名的地標特色是門前矗立著巨大的『招牌竹編蒸籠』與頂著十八摺抓褶、圓滾白嫩萌感十足的『巨型小籠包雕塑』，裊裊白煙迎接著饕客，是美軍眷舍區最具人氣的麵食點心代表。",
    "geoLat": 25.1378,
    "geoLon": 121.5472
  },
  {
    "id": "site_40",
    "code": "40",
    "name": "大衛小小羊 (David & Alpaca)",
    "category": "文化餐飲",
    "plusCode": "4GPR+PV",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 180,
    "y": 310,
    "radius": 40,
    "title": "40 大衛小小羊 (David & Alpaca)",
    "description": "座落於美軍宿舍草山星巴克正後方，是陽明山極受歡迎的草泥馬（羊駝）景觀餐廳！美軍眷舍改建的黃白歐風平房擁有綠意大草坪與白色木柵欄，兩隻個性溫馴親人的白色羊駝悠閒散步，大人小孩都能近距離互動餵食，是山仔后最療癒歡樂的童趣地標。",
    "geoLat": 25.13683,
    "geoLon": 121.54226
  },
  {
    "id": "site_41",
    "code": "41",
    "name": "朱里昂法式廚房 (C.L Program)",
    "category": "文化餐飲",
    "plusCode": "4GPR+CP",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 205,
    "y": 325,
    "radius": 40,
    "title": "41 朱里昂法式廚房 (C.L Program)",
    "description": "座落於國泰街與長春街口的美式鄉村鮮黃老木屋，以被譽為全台第一的頂級手工「法式可麗露 (Canelé)」與經典歐陸料理聞名。亮黃色的童話木質外牆、藍白相間遮陽棚與飄散著蘭姆酒、香草焦糖香氣的法式烘焙坊，是漫步美軍宿舍群不可錯過的甜蜜亮點。",
    "geoLat": 25.13606,
    "geoLon": 121.54344
  },
  {
    "id": "site_42",
    "code": "42",
    "name": "文化大學後山「情人坡」",
    "category": "夜景名勝",
    "plusCode": "4GPR+MJ",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 150,
    "y": 350,
    "radius": 45,
    "title": "42 文化大學後山「情人坡」",
    "description": "全台北無人不曉的夜景第一聖地！座落於文化大學體育館後方的下坡路段，視野無遮蔽一覽整座台北盆地、淡水河與台北101百萬燈火。斜坡草坪、雙人觀景木椅與路邊成排的約會機車，承載著無數華岡學子與情侶最浪漫的青春告白記憶。",
    "geoLat": 25.13665,
    "geoLon": 121.54111
  },
  {
    "id": "site_43",
    "code": "43",
    "name": "仇人坡 (荀子大道) 與百花池",
    "category": "校園名勝",
    "plusCode": "4GPR+PM",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 140,
    "y": 365,
    "radius": 45,
    "title": "43 仇人坡 (荀子大道) 與百花池",
    "description": "文化大學最具校園傳奇的代表性景觀！荀子大道上通往大恩館的超長好漢坡階梯，因坡度極陡、學生上下課爬得氣喘吁吁互看不順眼而戲稱為「仇人坡」。階梯頂端連接著大恩館前四季繁花盛開的經典「百花池」與中式八角涼亭，是每位華岡校友最深刻的青春印記。",
    "geoLat": 25.1368,
    "geoLon": 121.54009
  },
  {
    "id": "site_44",
    "code": "44",
    "name": "草山水管路步道 (愛富段出口)",
    "category": "自然步道",
    "plusCode": "4GPR+8C",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 180,
    "y": 150,
    "radius": 45,
    "title": "44 草山水管路步道 (愛富段出口)",
    "description": "全台少數被指定為「文化景觀」的世界級活水文化遺產！日治昭和三年（1928年）興建的草山水道系統，連接著愛富三街底的天母古道（水管路步道出口）。步道旁可見標誌性的巨大黑色高壓鑄鐵水管、古老石造排氣閥與調整池，流水潺潺綠蔭蔽日，是登山客自天母攀登至山仔后的綠意守護門戶。",
    "geoLat": 25.1407,
    "geoLon": 121.54344
  },
  {
    "id": "site_45",
    "code": "45",
    "name": "草山行館",
    "category": "歷史古蹟",
    "plusCode": "4GQ3+GQ",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 600,
    "y": 120,
    "radius": 45,
    "title": "45 草山行館",
    "description": "蔣公在台首座正式官邸（「草山第一官邸」）！原為 1920 年代日治臺灣糖業株式會社招待所，曾作為裕仁皇太子訪台御行啟下榻處。全檜木建造的雅緻日式黑瓦別墅，設有寬敞的日式迴廊緣側、幽靜茶室與美齡書房，依山而築俯瞰大台北盆地，是陽明山極具代表性的歷史文化名勝。",
    "geoLat": 25.15439099285714,
    "geoLon": 121.53803735
  },
  {
    "id": "site_46",
    "code": "46",
    "name": "文化大學大孝館 (圓柱體育館)",
    "category": "校園名勝",
    "plusCode": "4GPR+66",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 145,
    "y": 335,
    "radius": 45,
    "title": "46 文化大學大孝館 (圓柱體育館)",
    "description": "陽明山腰最宏偉壯觀的經典圓柱形建築！座落於中國文化大學校園核心的大孝館，是全校的綜合體育館，內部匯聚室內挑高籃球館、羽球館、排球場與體適能中心。其標誌性的巨型圓柱樓體、環狀採光帶與銀白鋼架圓穹頂，即使從山下士林、北投或大台北盆地各角落仰望陽明山山腰，都能第一眼看見這棟傲立山間的圓柱地標！",
    "geoLat": 25.13806,
    "geoLon": 121.54059
  },
  {
    "id": "site_47",
    "code": "47",
    "name": "草山夜未眠景觀餐廳",
    "category": "夜景名勝",
    "plusCode": "4GMQ+J6",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 135,
    "y": 840,
    "radius": 45,
    "title": "47 草山夜未眠景觀餐廳",
    "description": "全台北最浪漫夢幻的傳奇約會勝地！坐落於文化大學後山陡峭山崖邊，以「金色夢幻旋轉木馬」與凌空突出的「心形發光空中觀景台」聞名全台。環抱著百年相思老樹，層層柚木露台上設置舒適白色沙發卡座與高空發光吧台，正對著台北101與大台北盆地百萬璀璨夜景，是無數戀人告白與求婚的永恆愛情地標。",
    "geoLat": 25.13435,
    "geoLon": 121.54052
  },
  {
    "id": "site_48",
    "code": "48",
    "name": "陽明山順天府 (池府王爺)",
    "category": "宗教信仰",
    "plusCode": "4GPX+37",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 620,
    "y": 320,
    "radius": 40,
    "title": "48 陽明山順天府 (池府王爺)",
    "description": "陽明里建業聚落最重要的民間信仰中心！座落於建業路74巷山腰，主祀威靈顯赫的池府千歲（池府王爺）。廟貌保留傳統閩南紅磚燕尾紅瓦風貌，門前橫排懸掛成串象徵吉祥祈福的「順天府」大紅燈籠，門柱題有「國泰民安」「風調雨順」對聯，正殿前矗立大型三足天公香爐，香火鼎盛，長年庇佑山仔后、華岡學子與在地鄰里闔家平安。",
    "geoLat": 25.13767,
    "geoLon": 121.55064
  },
  {
    "id": "site_49",
    "code": "49",
    "name": "文化大學 大義館 (八角中庭宮殿)",
    "category": "校園名勝",
    "plusCode": "4GPR+5W",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 138,
    "y": 350,
    "radius": 45,
    "title": "49 文化大學 大義館 (八角中庭宮殿)",
    "description": "中國文化大學校園最核心的心臟地標！俯瞰呈現壯麗宏偉的「正八角形」中式宮殿樓體，中央巧妙內嵌巨型圓形採光天井中庭。為理學院與工學院的核心重鎮，內部匯聚尖端理工實驗室、階梯講堂與華岡微縮地質展區，雙層八角飛簷宮殿與中央迴廊氣勢磅礡，是每位華岡學子穿梭各館舍必經的中樞核心。",
    "geoLat": 25.138,
    "geoLon": 121.53988
  },
  {
    "id": "site_50",
    "code": "50",
    "name": "文化大學 大恩館 (行政大樓與百花池涼亭)",
    "category": "校園地標",
    "plusCode": "4GPR+3J",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 120,
    "y": 365,
    "radius": 40,
    "title": "50 文化大學 大恩館 (行政大樓與百花池涼亭)",
    "description": "文化大學最高行政樞紐大樓，樓高12層巍峨矗立於華岡之巔。頂層飾以中式琉璃金瓦大飛簷，樓內設有校長室、教務處與國際會議中心。大樓正面俯瞰著名的百花池八角木涼亭與噴泉花園，也是學子自仇人坡步入校園後映入眼簾的首座巍峨宮殿。",
    "geoLat": 25.13735,
    "geoLon": 121.53925
  },
  {
    "id": "site_51",
    "code": "51",
    "name": "文化大學 大賢館 (法學院與社科院)",
    "category": "校園地標",
    "plusCode": "4GPR+6V",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 155,
    "y": 355,
    "radius": 35,
    "title": "51 文化大學 大賢館 (法學院與社科院)",
    "description": "位於大義館南側、老子大道與朱子路環抱之學術重鎮。大賢館外觀典雅端莊，紅柱白牆、歇山式綠琉璃屋頂，為法學院與社會科學院之培育搖籃。樓前設有綠意庭園與石階步道，培育出無數台灣法界名家、司法官與社會學士。",
    "geoLat": 25.1378,
    "geoLon": 121.5408
  },
  {
    "id": "site_52",
    "code": "52",
    "name": "文化大學 大仁館 (十字風車綠瓦藝術學院)",
    "category": "校園名勝",
    "plusCode": "4GPR+8W",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 138,
    "y": 320,
    "radius": 45,
    "title": "52 文化大學 大仁館 (十字風車綠瓦藝術學院)",
    "description": "從空中俯瞰最震撼的華岡地標！呈現正十字星風車對稱翼樓架構，四面伸展延伸綠琉璃瓦大坡頂與雕樑飛簷。內部座落國際級『華岡大劇院』、音樂廳與舞蹈展演廳，是台灣藝術、國樂、戲劇與舞蹈頂尖人才的孕育搖籃，夜間在山林霧氣中宛如翡翠神殿。",
    "geoLat": 25.13885,
    "geoLon": 121.5398
  },
  {
    "id": "site_53",
    "code": "53",
    "name": "歐洲學校足球場 (戶外人工草皮)",
    "category": "休閒運動",
    "plusCode": "4GPX+FQ",
    "district": "east",
    "districtName": "東區・凱旋美軍山仔后",
    "x": 395,
    "y": 415,
    "radius": 40,
    "title": "53 歐洲學校足球場 (戶外人工草皮)",
    "description": "座落於凱旋路與國泰街交叉口、美軍俱樂部與美軍宿舍群環抱之國際標準戶外足球場。鋪設翠綠頂級人造草皮，劃設白色球門線與中圈禁區，兩側配備專業立體球門與金屬防護圍網，四周聳立高桿球場夜間探照燈。背倚壯闊大屯山與七星山群峰，常有各國學子與社區足球隊在此奔馳切磋，是山仔后最具朝氣的綠茵運動地標。",
    "geoLat": 25.1365,
    "geoLon": 121.5435
  },
  {
    "id": "site_54",
    "code": "54",
    "name": "山仔后文史工作室 (美軍宿舍文化景觀)",
    "category": "歷史古蹟",
    "plusCode": "4GPX+58",
    "district": "east",
    "districtName": "東區・愛富美軍宿舍群",
    "x": 260,
    "y": 265,
    "radius": 35,
    "title": "54 山仔后文史工作室 (美軍宿舍文化景觀)",
    "description": "座落於愛富二街北側、草山美軍眷舍核心腹地的文史倡議重鎮！長期致力於山仔后美軍宿舍群的文化資產保存，推動全台最大冷戰美軍聚落列為台北市文化景觀。建築本體由典型 1950 年代美式木造眷舍活化改建，白木雨淋板、紅磚煙囪與大木窗前廊古意盎然。館內典藏豐富的冷戰老照片、美軍眷屬生活史料與老地圖，門前設有美軍老郵筒與歷史導覽解說牌，是守護草山記憶的靈魂基地。",
    "geoLat": 25.13795,
    "geoLon": 121.5458
  },
  {
    "id": "site_55",
    "code": "55",
    "name": "文化大學 曉峯紀念館 (一樓全聯福利中心)",
    "category": "校園地標",
    "plusCode": "4GPR+9W",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 160,
    "y": 320,
    "radius": 45,
    "title": "55 文化大學 曉峯紀念館 (一樓全聯福利中心)",
    "description": "文化大學紀念創辦人張其昀先生（字曉峯）所建之十層宏偉總圖書館與資訊大樓！內部匯聚校史館、古籍珍本展與微縮典藏中心。最貼近師生日常的標誌特色，是一樓進駐的『全聯福利中心 PXmart 士林華岡店』，醒目的深藍色招牌、橘色圓形標誌、大落地玻璃自動滑門與整排金屬手推車，是全校學子每日課後採買零食、生鮮與生活必需品的校園生活大動脈！",
    "geoLat": 25.1384,
    "geoLon": 121.5404
  },
  {
    "id": "site_56",
    "code": "56",
    "name": "阿緹卡義大利 pizza專賣店 (Antica)",
    "category": "文化餐飲",
    "plusCode": "4GPR+PP",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 175,
    "y": 325,
    "radius": 40,
    "title": "56 阿緹卡義大利 pizza專賣店 (Antica)",
    "description": "座落於凱旋路與國泰街交界街廓、緊鄰凱旋路旁的美式老眷舍窯烤披薩與義大利麵名店！戶外擁有純白遮陽棚、悠閒木餐桌椅與綠意盆栽，最著名的地標特色是經典的拿坡里紅磚石砌圓頂披薩柴燒大烤爐，專賣正宗手擀薄脆羅馬方形披薩、經典義大利肉醬麵與海鮮燉飯，濃郁現烤起司香氣撲鼻，是陽明山極受歡迎的異國料理聚落。",
    "geoLat": 25.1367,
    "geoLon": 121.5424
  },
  {
    "id": "site_57",
    "code": "57",
    "name": "光在草山 (Light On Old Town)",
    "category": "文化餐飲",
    "plusCode": "4GPR+MQ",
    "district": "west",
    "districtName": "西區・文大與美軍俱樂部",
    "x": 185,
    "y": 335,
    "radius": 35,
    "title": "57 光在草山 (Light On Old Town)",
    "description": "座落於國泰街與凱旋路街廓南側、大衛小小羊與阿緹卡東南隔壁的草山文青老眷舍！保留深灰美軍木造建築雨淋板質感，配備整片落地採光玻璃窗與溫暖復古鎢絲吊燈串。提供頂級手沖單品咖啡、手作肉桂捲與戚風蛋糕，戶外設置原木露台與攝影打卡牆，是美軍眷舍聚落中極具藝術氣息的靜謐歇腳地。",
    "geoLat": 25.1365,
    "geoLon": 121.5426
  },
  {
    "id": "site_58",
    "code": "58",
    "name": "陽明山耶穌聖體堂 (天主教主徒會)",
    "category": "宗教信仰",
    "plusCode": "4GPR+QX",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 140,
    "y": 270,
    "radius": 40,
    "title": "58 陽明山耶穌聖體堂 (天主教主徒會)",
    "description": "座落於華岡路彎道外側、文化大學教職員宿舍與真愛桃花源北側的草山天主教神聖殿堂！與天主教主徒會總會院緊緊相依。最令人動容的地標標誌，是庭園中矗立的『黃柱八角聖母亭』，潔白莊嚴的聖母立像雙手合十垂憐祈福，四周環繞紅色鍛鐵欄杆與繁茂的紫紅景觀灌木花叢；後方禮拜堂立面純白聖潔，鐘樓頂端高聳金光十字架，長年為草山學子、神職人員與登山信友帶來心靈的撫慰與平靜。",
    "geoLat": 25.1386,
    "geoLon": 121.5432
  },
  {
    "id": "site_59",
    "code": "59",
    "name": "草山溫泉湯王池 (陽明山溫泉第一泉)",
    "category": "自然景觀",
    "plusCode": "4GQ3+MG",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 620,
    "y": 95,
    "radius": 40,
    "title": "59 草山溫泉湯王池 (陽明山溫泉第一泉)",
    "description": "陽明山歷史最悠久的天然硫磺溫泉源頭泉池！座落於青邨介壽堂與八卦升旗臺旁的幽靜山谷中。古樸厚實的青石砌成圓形八角大溫泉池，池內湛藍碧綠的滾燙天然硫磺原湯汩汩湧出，泉心終年熱氣騰騰、升騰著裊裊立體白煙與濃郁硫磺香氣。池邊保留日式木造湯之樋（引泉木管）、石燈籠與木格安全圍欄，是見證草山近百年溫泉療癒文史的活化石。",
    "geoLat": 25.1542,
    "geoLon": 121.5488
  },
  {
    "id": "site_60",
    "code": "60",
    "name": "陽明山中山樓",
    "category": "歷史古蹟",
    "plusCode": "4GQ4+83",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 640,
    "y": 70,
    "radius": 50,
    "title": "60 陽明山中山樓",
    "description": "正面朝南略偏西、面向紗帽山，由建築師修澤蘭設計的宮殿式建築，是陽明山的重要歷史地標。遊戲以綠瓦屋頂、白色基座、柱廊、圓形樓閣及入口石階表現其辨識特徵，並依地圖校正位置。 周邊以淡色泉水、石岸與蒸氣表現白磺溫泉地景；泉池位置是遊戲景觀示意，不代表實際泉源或開放泡湯設施。",
    "geoLat": 25.155733285714284,
    "geoLon": 121.55288110000001,
    "sourceUrl": "https://www.taiwan.nps.gov.tw/home/zh-tw/attractions/21185"
  },
  {
    "id": "site_61",
    "code": "61",
    "name": "前山公園・陽明湖",
    "category": "湖畔景觀",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 0,
    "y": 0,
    "radius": 40,
    "title": "61 前山公園・陽明湖",
    "description": "沿著陽明湖散步，認識前山公園的水景與湖中小島。遊戲保留地圖上的湖岸輪廓，加入石岸、樹蔭與觀景平台。",
    "geoLat": 25.14994,
    "geoLon": 121.5486578,
    "sourceUrl": "https://media.taiwan.net.tw/zh-tw/portal/travel/details/attraction_379000000a_002178"
  },
  {
    "id": "site_62",
    "code": "62",
    "name": "前山公園・磐流園",
    "category": "溫泉庭園",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 0,
    "y": 0,
    "radius": 40,
    "title": "62 前山公園・磐流園",
    "description": "前山公園的磐流園以水道、岩石與樹蔭構成庭園。遊戲以縮小的水道、石組與休憩亭呈現這處散步空間。",
    "geoLat": 25.150847765384615,
    "geoLon": 121.54828464615386,
    "sourceUrl": "https://media.taiwan.net.tw/zh-tw/portal/travel/details/attraction_379000000a_002178"
  },
  {
    "id": "site_63",
    "code": "63",
    "name": "陽明公園・花鐘",
    "category": "公園地標",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 0,
    "y": 0,
    "radius": 40,
    "title": "63 陽明公園・花鐘",
    "description": "陽明公園的花鐘是花季代表景觀。遊戲以圓形花壇、鐘面指針與環形花圃呈現，四周搭配賞花步道與樹林。",
    "geoLat": 25.159013715,
    "geoLon": 121.53900241000001,
    "sourceUrl": "https://travel.taipei/file/35634/"
  },
  {
    "id": "site_64",
    "code": "64",
    "name": "辛亥光復樓",
    "category": "歷史建築",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 0,
    "y": 0,
    "radius": 40,
    "title": "64 辛亥光復樓",
    "description": "位於陽明公園的兩層宮殿式建築，是公園的重要地標。遊戲以屋頂、柱廊與觀景平台表現建築輪廓。",
    "geoLat": 25.1596297,
    "geoLon": 121.53976935,
    "sourceUrl": "https://tcmb.culture.tw/zh-tw/detail?id=753902&indexCode=Culture_Media"
  },
  {
    "id": "site_65",
    "code": "65",
    "name": "陽明書屋・中興賓館",
    "category": "歷史建築",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 0,
    "y": 0,
    "radius": 40,
    "title": "65 陽明書屋・中興賓館",
    "description": "陽明書屋原名中興賓館，曾用於接待賓客與夏日避暑。遊戲以綠色外牆、兩層量體及林間庭園呈現，建築比例依遊玩需要縮小。",
    "geoLat": 25.162891458064518,
    "geoLon": 121.54078626774194,
    "sourceUrl": "https://www.taiwan.nps.gov.tw/home/zh-tw/attractions/20974.html"
  },
  {
    "id": "site_66",
    "code": "66",
    "name": "陽明山國家公園遊客中心",
    "category": "遊客服務",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 0,
    "y": 0,
    "radius": 40,
    "title": "66 陽明山國家公園遊客中心",
    "description": "陽明山國家公園的主要遊客服務據點之一。這裡可以作為探索公園區的起點；遊戲中的建築採入口大廳與庭園的風格化示意。",
    "geoLat": 25.155421583333332,
    "geoLon": 121.54669205,
    "sourceUrl": "https://www.ymsnp.gov.tw/ch/specialreport/accessible-travel/142"
  },
  {
    "id": "site_67",
    "code": "67",
    "name": "陽明公園前門",
    "category": "公園入口",
    "district": "yangmingshan",
    "districtName": "陽明山公園區",
    "x": 0,
    "y": 0,
    "radius": 40,
    "title": "67 陽明公園前門",
    "description": "從公園前門進入陽明公園，沿園內步道探索花鐘與辛亥光復樓。遊戲以入口牌樓、步道與花木作為這段旅程的起點。",
    "geoLat": 25.1546656,
    "geoLon": 121.53915923846154,
    "sourceUrl": "https://www.travel.taipei/zh-tw/attraction/details/414"
  }
];
