/**
 * 台北市士林區陽明里 官方全域 30 處核心地標空間資料庫
 * 精準錨定於 1024 x 1024 純手繪水彩繪本全景地圖各建築物正門
 * 功能導向模式：單純描述「這個地方是幹嘛的」、功能與遊憩體驗，無生硬特色標籤
 */
export const LANDMARKS = [
  {
    "id": "site_01",
    "code": "01",
    "name": "山仔后派出所",
    "category": "公共安全",
    "plusCode": "4GPW+WG",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 310,
    "y": 405,
    "radius": 40,
    "title": "01 山仔后派出所",
    "description": "山仔后交通與生活樞紐的治安守護站，提供登山旅客急難救助、問路指引與居民在地警政服務的安全據點。",
    "geoLat": 25.13725,
    "geoLon": 121.54625
  },
  {
    "id": "site_02",
    "code": "02",
    "name": "陽明山麥當勞",
    "category": "生活餐飲",
    "plusCode": "4GPW+RC",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 300,
    "y": 445,
    "radius": 40,
    "title": "02 陽明山麥當勞",
    "description": "陪伴文化大學師生與遊客近 37 年的經典地標，是無數人上山約見面集合、吃早餐吹冷氣與等公車的共同青春回憶。",
    "geoLat": 25.137,
    "geoLon": 121.546
  },
  {
    "id": "site_03",
    "code": "03",
    "name": "7-ELEVEN 陽明山門市",
    "category": "生活機能",
    "plusCode": "4GPW+QH",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 410,
    "y": 425,
    "radius": 40,
    "title": "03 7-ELEVEN 陽明山門市",
    "description": "山仔后最熱鬧的 24 小時生活補給站，無論是上山賞花、爬山健行或文大學生深夜消夜，都能隨時採買熱食、零食與日常用品。",
    "geoLat": 25.13687,
    "geoLon": 121.54638
  },
  {
    "id": "site_04",
    "code": "04",
    "name": "山仔后公園",
    "category": "公共綠地",
    "plusCode": "4GPW+V7",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 230,
    "y": 315,
    "radius": 40,
    "title": "04 山仔后公園",
    "description": "隱身在熱鬧街道旁的社區小綠洲，設有林蔭涼亭與長椅，供附近居民晨昏散步、鄰里聊天歇腳與親子戶外活動。",
    "geoLat": 25.13712,
    "geoLon": 121.54563
  },
  {
    "id": "site_05",
    "code": "05",
    "name": "陽明里辦公處 (區民活動中心)",
    "category": "社區服務",
    "plusCode": "4GPW+5W",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 315,
    "y": 295,
    "radius": 40,
    "title": "05 陽明里辦公處 (區民活動中心)",
    "description": "陽明里的在地生活與行政核心，舉辦長青講座、里民聚會與各項公共活動，也是走訪完全里 30 處地標領取榮譽里民證的地方。",
    "geoLat": 25.13537,
    "geoLon": 121.54725
  },
  {
    "id": "site_06",
    "code": "06",
    "name": "台灣中油陽明山加油站",
    "category": "交通補給",
    "plusCode": "4GPW+68",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 328,
    "y": 500,
    "radius": 40,
    "title": "06 台灣中油陽明山加油站",
    "description": "陽明山上極少數的加油補給站，開車或騎車上山賞花、追雪、前往擎天崗或竹子湖前，必定停靠把油箱加滿的地方。",
    "geoLat": 25.1355,
    "geoLon": 121.54575
  },
  {
    "id": "site_07",
    "code": "07",
    "name": "豆留森林 (CAMA)",
    "category": "文化餐飲",
    "plusCode": "4GQW+7M",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 376,
    "y": 168,
    "radius": 40,
    "title": "07 豆留森林 (CAMA)",
    "description": "結合昭和日式老官舍與六百坪幽靜竹林的景觀咖啡旗艦店，讓人置身和風庭院中享用精品手沖咖啡、烘豆體驗與早午餐。",
    "geoLat": 25.13812,
    "geoLon": 121.54663
  },
  {
    "id": "site_08",
    "code": "08",
    "name": "白房子 Yang Ming Cafe",
    "category": "歷史餐飲",
    "plusCode": "4GQW+2C",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 265,
    "y": 188,
    "radius": 40,
    "title": "08 白房子 Yang Ming Cafe",
    "description": "美軍眷舍老洋房改建的純白歐風咖啡館，提供精緻排餐、現烤手工麵包與手沖咖啡，適合朋友聚會、約會與享受悠閒午後。",
    "geoLat": 25.1375,
    "geoLon": 121.546
  },
  {
    "id": "site_09",
    "code": "09",
    "name": "彩虹谷故事館 (F206)",
    "category": "文史故事",
    "plusCode": "4GQW+45",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 135,
    "y": 265,
    "radius": 40,
    "title": "09 彩虹谷故事館 (F206)",
    "description": "原汁原味保留 1950 年代美軍眷舍原貌的文史老屋，推廣冷戰美軍生活記憶、老屋修復故事，並能在此欣賞陽明山世界級的壯觀彩虹景觀。",
    "geoLat": 25.13775,
    "geoLon": 121.54538
  },
  {
    "id": "site_10",
    "code": "10",
    "name": "美軍宿舍群 (C 區建業路段)",
    "category": "文創聚落",
    "plusCode": "4GPX+RH",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 205,
    "y": 135,
    "radius": 40,
    "title": "10 美軍宿舍群 (C 區建業路段)",
    "description": "全台保存最完整的美式冷戰官兵聚落，兩側有著大煙囪、寬廣草坪與美式平房，是散步拍照、感受美式鄉村街區氛圍的文創漫遊區。",
    "geoLat": 25.137,
    "geoLon": 121.54888
  },
  {
    "id": "site_11",
    "code": "11",
    "name": "雀客藏居陽明山溫泉飯店",
    "category": "溫泉名宿",
    "plusCode": "5G2W+27",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 500,
    "y": 145,
    "radius": 40,
    "title": "11 雀客藏居陽明山溫泉飯店",
    "description": "草山知名的山中溫泉渡假飯店，提供天然純淨的白磺溫泉泡湯、山景客房與中西式美饌，供旅客遠離塵囂放鬆身心。",
    "geoLat": 25.15,
    "geoLon": 121.54563
  },
  {
    "id": "site_12",
    "code": "12",
    "name": "陽明山錫安堂",
    "category": "宗教聖所",
    "plusCode": "4GXX+QV",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 620,
    "y": 195,
    "radius": 40,
    "title": "12 陽明山錫安堂",
    "description": "隱身在山林綠意中的寧靜純白教堂，為在地居民與大學生提供主日崇拜、心靈團契與安靜沉澱心靈的信仰避風港。",
    "geoLat": 25.14937,
    "geoLon": 121.54962
  },
  {
    "id": "site_13",
    "code": "13",
    "name": "草山御賓館 (市定古蹟)",
    "category": "市定古蹟",
    "plusCode": "5H22+99",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 375,
    "y": 75,
    "radius": 40,
    "title": "13 草山御賓館 (市定古蹟)",
    "description": "日治時期為接待裕仁皇太子所建的和洋風官邸，後為孫科院長寓所，是陽明山極具代表性的市定古蹟，讓人近距離見證草山近百年政局文史風雲。",
    "geoLat": 25.15087,
    "geoLon": 121.55088
  },
  {
    "id": "site_14",
    "code": "14",
    "name": "中國文化大學",
    "category": "大專學園",
    "plusCode": "4GPQ+JP",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 100,
    "y": 345,
    "radius": 40,
    "title": "14 中國文化大學",
    "description": "座落在海拔 400 公尺華岡之巔的高等學府，擁有全台最雄偉的中國宮殿式校舍群，也是情侶與遊客看夜景、俯瞰整個大台北盆地景緻的勝地。",
    "geoLat": 25.1365,
    "geoLon": 121.53925
  },
  {
    "id": "site_15",
    "code": "15",
    "name": "亞尼克夢想村",
    "category": "美式甜點",
    "plusCode": "4GPV+JF",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 105,
    "y": 420,
    "radius": 40,
    "title": "15 亞尼克夢想村",
    "description": "由美軍老眷舍改造的超人氣美式烘焙甜點坊，專賣各式招牌現烤派塔、生乳捲與野餐點心，能坐在戶外庭院大樹下享受美式鄉村午茶。",
    "geoLat": 25.1365,
    "geoLon": 121.54363
  },
  {
    "id": "site_16",
    "code": "16",
    "name": "The Cafe By 想 陽明山",
    "category": "文化餐飲",
    "plusCode": "4GPV+FV",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 105,
    "y": 560,
    "radius": 40,
    "title": "16 The Cafe By 想 陽明山",
    "description": "群山環抱中的亮黃色歐風木屋景觀餐廳，擁有落羽松庭園與水池造景，提供義大利麵、早午餐與鬆餅，是拍照打卡與放鬆聚餐的好去處。",
    "geoLat": 25.13612,
    "geoLon": 121.54462
  },
  {
    "id": "site_17",
    "code": "17",
    "name": "陽明山星巴克 (草山門市)",
    "category": "文創名店",
    "plusCode": "4GPV+F5",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 215,
    "y": 515,
    "radius": 40,
    "title": "17 陽明山星巴克 (草山門市)",
    "description": "改建自美軍眷舍的純白木屋咖啡館，完整保留復古紅磚大壁爐與戶外草地櫻花樹，讓人坐在老房子裡喝咖啡、感受美式度假風情。",
    "geoLat": 25.13612,
    "geoLon": 121.54288
  },
  {
    "id": "site_18",
    "code": "18",
    "name": "美軍俱樂部 (BRICK YARD)",
    "category": "歷史餐飲",
    "plusCode": "4GPV+69",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 350,
    "y": 600,
    "radius": 40,
    "title": "18 美軍俱樂部 (BRICK YARD)",
    "description": "原美軍聯誼俱樂部改建的千坪文創休閒聚落，結合美式炭烤餐廳、戶外露天泳池水景與數千張珍貴黑膠唱片展覽，重現冷戰黃金年代。",
    "geoLat": 25.1355,
    "geoLon": 121.54338
  },
  {
    "id": "site_19",
    "code": "19",
    "name": "陽明山美國渡假村",
    "category": "美式別墅",
    "plusCode": "4GPR+CM",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 175,
    "y": 620,
    "radius": 40,
    "title": "19 陽明山美國渡假村",
    "description": "保留高階軍官眷舍規格的獨棟包棟式渡假園區，擁有獨立大院子、綠意草坪、戶外鞦韆與烤肉設備，適合親友家庭體驗道地美式郊區生活。",
    "geoLat": 25.136,
    "geoLon": 121.54163
  },
  {
    "id": "site_20",
    "code": "20",
    "name": "臺北市立陽明教養院",
    "category": "社福公義",
    "plusCode": "4GPR+53",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 80,
    "y": 705,
    "radius": 40,
    "title": "20 臺北市立陽明教養院",
    "description": "深耕山林間的公立身心障礙全人照護家園，提供中重度心智障礙學員溫暖專業的生活照料、技能陶冶與社區關懷服務。",
    "geoLat": 25.13537,
    "geoLon": 121.54013
  },
  {
    "id": "site_21",
    "code": "21",
    "name": "屋頂上餐廳 (The Top)",
    "category": "夜景地標",
    "plusCode": "4GMQ+VM",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 125,
    "y": 825,
    "radius": 40,
    "title": "21 屋頂上餐廳 (The Top)",
    "description": "依山壁而建的梯田式南洋峇里島風觀景餐廳，設有發呆亭與無邊際水池，是全台北最具指標性的百萬夜景約會與跨年勝地。",
    "geoLat": 25.13462,
    "geoLon": 121.53913
  },
  {
    "id": "site_22",
    "code": "22",
    "name": "華岡藝校",
    "category": "藝術學園",
    "plusCode": "4GPX+RH",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 555,
    "y": 285,
    "radius": 40,
    "title": "22 華岡藝校",
    "description": "台灣歷史悠久的表演藝術名校，培養無數知名歌手、演員與舞者，走在校門周邊常能聽見學子練琴、排戲與練習歌唱的藝術氛圍。",
    "geoLat": 25.137,
    "geoLon": 121.54888
  },
  {
    "id": "site_23",
    "code": "23",
    "name": "台北歐洲學校 (陽明校區)",
    "category": "國際教育",
    "plusCode": "4GPX+MJ",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 590,
    "y": 360,
    "radius": 40,
    "title": "23 台北歐洲學校 (陽明校區)",
    "description": "匯聚英、法、德跨國教育的小學部校區，美麗的歐風紅瓦斜頂校舍融入草山大自然，為駐台外籍人士與各國學子打造國際化的學習環境。",
    "geoLat": 25.13662,
    "geoLon": 121.549
  },
  {
    "id": "site_24",
    "code": "24",
    "name": "草山猛禽中心",
    "category": "自然生態",
    "plusCode": "4GPX+PJ",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 585,
    "y": 495,
    "radius": 40,
    "title": "24 草山猛禽中心",
    "description": "推廣台灣猛禽保育與救傷的自然教育中心，能認識大冠鷲、鳳頭蒼鷹等在陽明山盤旋的空中霸主，並提供生態講座與望遠鏡觀鳥體驗。",
    "geoLat": 25.13675,
    "geoLon": 121.549
  },
  {
    "id": "site_25",
    "code": "25",
    "name": "YMS onefifteen 初衣食午",
    "category": "時尚選品",
    "plusCode": "4GPX+77",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 565,
    "y": 615,
    "radius": 40,
    "title": "25 YMS onefifteen 初衣食午",
    "description": "讓都市人上山放慢步調、結合美食、藝術、住宿與自然美學的高檔美軍宿舍改建聚落。",
    "geoLat": 25.13562,
    "geoLon": 121.54813
  },
  {
    "id": "site_26",
    "code": "26",
    "name": "花卉試驗中心",
    "category": "自然生態",
    "plusCode": "4GPW+33",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 225,
    "y": 755,
    "radius": 40,
    "title": "26 花卉試驗中心",
    "description": "台北市免門票的公立植物公園，佔地廣大且四季百花盛開，擁有全台聞名的百年茶花林步道與櫻花大道，是散步健行與婚紗拍攝的賞花勝地。",
    "geoLat": 25.13512,
    "geoLon": 121.54513
  },
  {
    "id": "site_27",
    "code": "27",
    "name": "陽明福德宮",
    "category": "民間信仰",
    "plusCode": "4GPW+26",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 345,
    "y": 725,
    "radius": 40,
    "title": "27 陽明福德宮",
    "description": "花卉試驗中心對面的百年土地公廟，是在地里民出入保平安、農作生意興隆的精神寄託，登山客與過路人也常在此停步參拜祈福。",
    "geoLat": 25.135,
    "geoLon": 121.5455
  },
  {
    "id": "site_28",
    "code": "28",
    "name": "臺北市立格致國民中學",
    "category": "初級教育",
    "plusCode": "4GJW+WW",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 350,
    "y": 860,
    "radius": 40,
    "title": "28 臺北市立格致國民中學",
    "description": "隱身在山林綠蔭間的森林生態國中，校園擁有極高的綠覆率與遠眺台北視野，為山仔后在地子弟提供自然健康的求學成長環境。",
    "geoLat": 25.13225,
    "geoLon": 121.54725
  },
  {
    "id": "site_29",
    "code": "29",
    "name": "納美花園 (Navi Garden)",
    "category": "休閒莊園",
    "plusCode": "4GQ2+3M",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 530,
    "y": 760,
    "radius": 40,
    "title": "29 納美花園 (Navi Garden)",
    "description": "佔地六千坪的世外桃源休閒莊園，擁有遼闊的碧綠大草皮、生態池塘與林蔭落葉步道，專門提供浪漫的戶外森林系婚禮、草地野餐與聚會空間。",
    "geoLat": 25.1385,
    "geoLon": 121.554
  },
  {
    "id": "site_30",
    "code": "30",
    "name": "下竹林福德宮",
    "category": "民間信仰",
    "plusCode": "4GJW+7F",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 560,
    "y": 890,
    "radius": 40,
    "title": "30 下竹林福德宮",
    "description": "由市區沿仰德大道進入陽明山的第一道守護小廟，石造古祠隱身於幽靜竹林與老樹旁，百年來默默守護每位登山健行者與歸鄉居民。",
    "geoLat": 25.13062,
    "geoLon": 121.54613
  }
];
