/**
 * 台北市士林區陽明里 官方全域 30 處核心地標空間資料庫
 * 精準錨定於 1024 x 1024 純手繪水彩繪本全景地圖各建築物正門
 * 純淨模式：無地址、無專屬特色標籤、無文史特點標籤，純粹客觀描述各場所實體本質
 */
export const LANDMARKS = [
  {
    "id": "site_01",
    "code": "01",
    "name": "山仔后派出所",
    "category": "公共安全",
    "plusCode": "4GPW+WG",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 310,
    "y": 405,
    "radius": 40,
    "title": "01 山仔后派出所",
    "description": "臺北市政府警察局士林分局轄下的派出所，座落於格致路與光華路交叉路口，負責陽明山山仔后地區、文化大學周邊的治安維護、交通疏導與在地居民生活服務。",
    "geoLat": 25.13725,
    "geoLon": 121.54625
  },
  {
    "id": "site_02",
    "code": "02",
    "name": "陽明山麥當勞",
    "category": "生活餐飲",
    "plusCode": "4GPW+RC",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 300,
    "y": 445,
    "radius": 40,
    "title": "02 陽明山麥當勞",
    "description": "位於格致路與光華路口的美式連鎖速食餐廳，自 1986 年起營運近 37 年，是數十年來文化大學學生、華岡藝校師生與陽明山遊客最熟悉的經典聚會與集合地標。",
    "geoLat": 25.137,
    "geoLon": 121.546
  },
  {
    "id": "site_03",
    "code": "03",
    "name": "7-ELEVEN 陽明山門市",
    "category": "生活機能",
    "plusCode": "4GPW+QH",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 410,
    "y": 425,
    "radius": 40,
    "title": "03 7-ELEVEN 陽明山門市",
    "description": "位於山仔后公車站旁的 24 小時便利商店，正對麥當勞舊址，提供周邊社區里民、文大師生與登山遊客全天候的生活補給、餐飲與便民服務。",
    "geoLat": 25.13687,
    "geoLon": 121.54638
  },
  {
    "id": "site_04",
    "code": "04",
    "name": "山仔后公園",
    "category": "公共綠地",
    "plusCode": "4GPW+V7",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 230,
    "y": 315,
    "radius": 40,
    "title": "04 山仔后公園",
    "description": "位於山仔后派出所正後方、光華路旁的社區鄰里公園，園內設有綠蔭涼亭、休閒步道與休憩長椅，為在地里民散步、休憩與鄰里交流的綠地空間。",
    "geoLat": 25.13712,
    "geoLon": 121.54563
  },
  {
    "id": "site_05",
    "code": "05",
    "name": "陽明里辦公處 (區民活動中心)",
    "category": "社區服務",
    "plusCode": "4GPW+5W",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 315,
    "y": 295,
    "radius": 40,
    "title": "05 陽明里辦公處 (區民活動中心)",
    "description": "臺北市士林區陽明里的里民活動中心與里長辦公室所在地，定期舉辦社區課程、藝文活動與公共會議，為全里最重要的社區公共服務核心。",
    "geoLat": 25.13537,
    "geoLon": 121.54725
  },
  {
    "id": "site_06",
    "code": "06",
    "name": "台灣中油陽明山加油站",
    "category": "交通補給",
    "plusCode": "4GPW+68",
    "district": "central",
    "districtName": "中央・山仔后生活核心",
    "x": 328,
    "y": 500,
    "radius": 40,
    "title": "06 台灣中油陽明山加油站",
    "description": "台灣中油直營的加油站，位於格致路與菁山路口下方，是陽明山山仔后一帶最重要的加油與車輛能源補給站，服務上下山的各式汽機車輛。",
    "geoLat": 25.1355,
    "geoLon": 121.54575
  },
  {
    "id": "site_07",
    "code": "07",
    "name": "豆留森林 (CAMA)",
    "category": "文化餐飲",
    "plusCode": "4GQW+7M",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 376,
    "y": 168,
    "radius": 40,
    "title": "07 豆留森林 (CAMA)",
    "description": "由 CAMA 咖啡打造的品牌旗艦店，原為 1937 年昭和時期的台灣總督府農林專門學校宿舍，經台北市文化局老房子文化運動修復，是一座結合六百坪竹林庭園與日式木造建築的咖啡名所。",
    "geoLat": 25.13812,
    "geoLon": 121.54663
  },
  {
    "id": "site_08",
    "code": "08",
    "name": "白房子 Yang Ming Cafe",
    "category": "歷史餐飲",
    "plusCode": "4GQW+2C",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 265,
    "y": 188,
    "radius": 40,
    "title": "08 白房子 Yang Ming Cafe",
    "description": "由美軍眷舍老洋房改建而成的知名咖啡餐廳，外觀為純白色歐風平房，內部保留美式壁爐與復古家具，提供手沖咖啡、排餐與現烤麵包，是山仔后深具人氣的用餐休閒去處。",
    "geoLat": 25.1375,
    "geoLon": 121.546
  },
  {
    "id": "site_09",
    "code": "09",
    "name": "彩虹谷故事館 (F206)",
    "category": "文史故事",
    "plusCode": "4GQW+45",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 135,
    "y": 265,
    "radius": 40,
    "title": "09 彩虹谷故事館 (F206)",
    "description": "位於愛富三街美軍眷舍群 F 區的文史據點，以原貌原材保留 1950 年代美軍眷舍建築，館內展示山仔后冷戰美軍歷史、老屋修復歷程與陽明山著名的彩虹文化。",
    "geoLat": 25.13775,
    "geoLon": 121.54538
  },
  {
    "id": "site_10",
    "code": "10",
    "name": "美軍宿舍群 (C 區建業路段)",
    "category": "文創聚落",
    "plusCode": "4GPX+RH",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 205,
    "y": 135,
    "radius": 40,
    "title": "10 美軍宿舍群 (C 區建業路段)",
    "description": "1950 年代冷戰時期駐台美軍顧問團軍官與眷屬居住的宿舍群，分佈於建業路兩側，保有典型北美郊區平房洋屋、壁爐煙囪與開闊草坪庭院，為全台規模最大的美式建築文化景觀聚落。",
    "geoLat": 25.137,
    "geoLon": 121.54888
  },
  {
    "id": "site_11",
    "code": "11",
    "name": "雀客藏居陽明山溫泉飯店",
    "category": "溫泉名宿",
    "plusCode": "5G2W+27",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 500,
    "y": 145,
    "radius": 40,
    "title": "11 雀客藏居陽明山溫泉飯店",
    "description": "位於格致路上的知名溫泉渡假飯店，前身為中國麗緻大飯店，坐擁陽明山群山自然景觀，擁有天然純淨的白磺溫泉池與多間景觀客房，是草山歷史悠久的渡假名宿。",
    "geoLat": 25.15,
    "geoLon": 121.54563
  },
  {
    "id": "site_12",
    "code": "12",
    "name": "陽明山錫安堂",
    "category": "宗教聖所",
    "plusCode": "4GXX+QV",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 620,
    "y": 195,
    "radius": 40,
    "title": "12 陽明山錫安堂",
    "description": "台灣信義會轄下的基督教教會，座落於陽明路一段山林幽靜處，外觀為純白色尖頂教堂，長年為陽明山地區居民與大專青年提供主日崇拜、心靈團契與社區關懷服務。",
    "geoLat": 25.14937,
    "geoLon": 121.54962
  },
  {
    "id": "site_13",
    "code": "13",
    "name": "草山御賓館 (國定古蹟)",
    "category": "國定古蹟",
    "plusCode": "5H22+99",
    "district": "north",
    "districtName": "北區・草山歷史官舍",
    "x": 375,
    "y": 75,
    "radius": 40,
    "title": "13 草山御賓館 (國定古蹟)",
    "description": "興建於 1923 年大正時期的日治和洋折衷風格官邸，曾為接待日本裕仁皇太子訪台之草山御召所，戰後曾作為蔣介石寓所與孫科院長官邸，為陽明山地區重要的國定古蹟。",
    "geoLat": 25.15087,
    "geoLon": 121.55088
  },
  {
    "id": "site_14",
    "code": "14",
    "name": "中國文化大學",
    "category": "大專學園",
    "plusCode": "4GPQ+JP",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 100,
    "y": 345,
    "radius": 40,
    "title": "14 中國文化大學",
    "description": "創立於 1962 年的私立綜合大學，校園座落於陽明山山仔后華岡台地，擁有全台灣最宏偉的中華傳統宮殿式建築校舍群，地勢高亢，可俯瞰大台北盆地與淡水河美景。",
    "geoLat": 25.1365,
    "geoLon": 121.53925
  },
  {
    "id": "site_15",
    "code": "15",
    "name": "亞尼克夢想村",
    "category": "美式甜點",
    "plusCode": "4GPV+JF",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 105,
    "y": 420,
    "radius": 40,
    "title": "15 亞尼克夢想村",
    "description": "位於長春街美軍宿舍群中的烘焙甜點專賣店，將 1950 年代美軍老眷舍改造為美式鄉村風格空間，主打各式美式現烤派塔、生乳捲與下午茶點心，並設有戶外野餐庭園。",
    "geoLat": 25.1365,
    "geoLon": 121.54363
  },
  {
    "id": "site_16",
    "code": "16",
    "name": "The Cafe By 想 陽明山",
    "category": "文化餐飲",
    "plusCode": "4GPV+FV",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 105,
    "y": 560,
    "radius": 40,
    "title": "16 The Cafe By 想 陽明山",
    "description": "位於國泰街美軍眷舍區的熱門景觀咖啡餐廳，由兩棟亮黃色美式雙拼木屋改建而成，庭園栽植落羽松與噴泉造景，提供義大利麵、咖啡與輕食，環境優雅舒適。",
    "geoLat": 25.13612,
    "geoLon": 121.54462
  },
  {
    "id": "site_17",
    "code": "17",
    "name": "陽明山星巴克 (草山門市)",
    "category": "文創名店",
    "plusCode": "4GPV+F5",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 215,
    "y": 515,
    "radius": 40,
    "title": "17 陽明山星巴克 (草山門市)",
    "description": "台灣星巴克最具代表性的特色門市之一，改建自 1950 年代美軍眷舍，外觀為純白色美式木造平房，室內完整保留紅磚壁爐大煙囪，戶外設有綠地與櫻花露天座。",
    "geoLat": 25.13612,
    "geoLon": 121.54288
  },
  {
    "id": "site_18",
    "code": "18",
    "name": "美軍俱樂部 (BRICK YARD)",
    "category": "歷史餐飲",
    "plusCode": "4GPV+69",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 350,
    "y": 600,
    "radius": 40,
    "title": "18 美軍俱樂部 (BRICK YARD)",
    "description": "佔地近千坪的文化餐飲休閒園區，前身為冷戰時期駐台美軍通訊中心的俱樂部，保留了美式紅磚建築、大煙囪、戶外水池與豐富的西洋黑膠唱片收藏。",
    "geoLat": 25.1355,
    "geoLon": 121.54338
  },
  {
    "id": "site_19",
    "code": "19",
    "name": "陽明山美國渡假村",
    "category": "美式別墅",
    "plusCode": "4GPR+CM",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 175,
    "y": 620,
    "radius": 40,
    "title": "19 陽明山美國渡假村",
    "description": "位於凱旋路的美式別墅渡假園區，將美軍高階軍官眷舍整修為獨棟渡假木屋，保留獨立寬敞庭院、草坪鞦韆與戶外烤肉設施，提供家庭與團體包棟體驗美式郊區生活。",
    "geoLat": 25.136,
    "geoLon": 121.54163
  },
  {
    "id": "site_20",
    "code": "20",
    "name": "臺北市立陽明教養院",
    "category": "社福公義",
    "plusCode": "4GPR+53",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 80,
    "y": 705,
    "radius": 40,
    "title": "20 臺北市立陽明教養院",
    "description": "臺北市政府社會局所屬的公立全日型身心障礙福利機構，位於凱旋路幽靜林間，為中重度身心障礙學員提供全人生活照顧、生活自理培訓、技能陶冶與復健照護。",
    "geoLat": 25.13537,
    "geoLon": 121.54013
  },
  {
    "id": "site_21",
    "code": "21",
    "name": "屋頂上餐廳 (The Top)",
    "category": "夜景地標",
    "plusCode": "4GMQ+VM",
    "district": "west",
    "districtName": "西區・華岡美軍生活圈",
    "x": 125,
    "y": 825,
    "radius": 40,
    "title": "21 屋頂上餐廳 (The Top)",
    "description": "位於文化大學下方邊坡的梯田式夜景休閒餐廳，以南洋峇里島風發呆亭、帳篷與無邊際水池為特色，擁有開闊俯瞰大台北盆地、台北 101 與淡水河出海口的百萬夜景視野。",
    "geoLat": 25.13462,
    "geoLon": 121.53913
  },
  {
    "id": "site_22",
    "code": "22",
    "name": "華岡藝校",
    "category": "藝術學園",
    "plusCode": "4GPX+RH",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 555,
    "y": 285,
    "radius": 40,
    "title": "22 華岡藝校",
    "description": "位於建業路的著名私立藝術高中，設有戲劇科、舞蹈科、音樂科與表演藝術科，數十年來培育出眾多華語流行文化、影視戲劇與表演藝術領域的優秀專業人才。",
    "geoLat": 25.137,
    "geoLon": 121.54888
  },
  {
    "id": "site_23",
    "code": "23",
    "name": "台北歐洲學校 (陽明校區)",
    "category": "國際教育",
    "plusCode": "4GPX+MJ",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 590,
    "y": 360,
    "radius": 40,
    "title": "23 台北歐洲學校 (陽明校區)",
    "description": "位於建業路的非營利國際學校，涵蓋英國部、德國部與法國部，陽明校區主要為小學部學生，提供多元文化與雙語教育，服務眾多在台外籍專業人士與外交使節子女。",
    "geoLat": 25.13662,
    "geoLon": 121.549
  },
  {
    "id": "site_24",
    "code": "24",
    "name": "草山猛禽中心",
    "category": "自然生態",
    "plusCode": "4GPX+PJ",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 585,
    "y": 495,
    "radius": 40,
    "title": "24 草山猛禽中心",
    "description": "台灣猛禽研究會設立於陽明山的猛禽生態推廣中心，由老建築整建而成，專門進行大冠鷲、鳳頭蒼鷹等台灣猛禽的生態調查、傷鳥救傷諮詢與大眾野鳥保育教育。",
    "geoLat": 25.13675,
    "geoLon": 121.549
  },
  {
    "id": "site_25",
    "code": "25",
    "name": "YMS onefifteen 初衣食午",
    "category": "時尚選品",
    "plusCode": "4GPX+77",
    "district": "east",
    "districtName": "東區・建業學園與生態",
    "x": 565,
    "y": 615,
    "radius": 40,
    "title": "25 YMS onefifteen 初衣食午",
    "description": "位於愛富一街與建業路口的高端生活風格概念店，將美軍老平房與現代玻璃溫室建築結合，匯聚國內外設計師服飾、香氛保養品與法式香草料理輕食。",
    "geoLat": 25.13562,
    "geoLon": 121.54813
  },
  {
    "id": "site_26",
    "code": "26",
    "name": "花卉試驗中心",
    "category": "自然生態",
    "plusCode": "4GPW+33",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 225,
    "y": 755,
    "radius": 40,
    "title": "26 花卉試驗中心",
    "description": "臺北市政府工務局公園路燈工程管理處轄下的植物試驗基地，佔地約 4 公頃，園內長年培育茶花、櫻花、杜鵑等各式花卉，擁有著名的百年茶花步道，為市民免費散步與賞花勝地。",
    "geoLat": 25.13512,
    "geoLon": 121.54513
  },
  {
    "id": "site_27",
    "code": "27",
    "name": "陽明福德宮",
    "category": "民間信仰",
    "plusCode": "4GPW+26",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 345,
    "y": 725,
    "radius": 40,
    "title": "27 陽明福德宮",
    "description": "位於仰德大道四段 175 巷口旁的老土地公廟，正對花卉試驗中心大門，廟貌莊嚴小巧、香火鼎盛，長年庇佑陽明里居民出入平安與行旅順遂，是在地深具人情味的信仰寄託。",
    "geoLat": 25.135,
    "geoLon": 121.5455
  },
  {
    "id": "site_28",
    "code": "28",
    "name": "臺北市立格致國民中學",
    "category": "初級教育",
    "plusCode": "4GJW+WW",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 350,
    "y": 860,
    "radius": 40,
    "title": "28 臺北市立格致國民中學",
    "description": "臺北市士林區的公立國民中學，校園依山而建，四周群山環抱、樹木蓊鬱，是一所擁有優質自然生態環境與多元社團活動的綠色森林國中。",
    "geoLat": 25.13225,
    "geoLon": 121.54725
  },
  {
    "id": "site_29",
    "code": "29",
    "name": "納美花園 (Navi Garden)",
    "category": "休閒莊園",
    "plusCode": "4GQ2+3M",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 530,
    "y": 760,
    "radius": 40,
    "title": "29 納美花園 (Navi Garden)",
    "description": "隱身於菁山路山谷間的休閒莊園，佔地約六千坪，園區內擁有大片修剪整齊的綠茵草皮、林間步道與生態池塘，提供戶外森系婚禮、草地野餐與休閒餐飲服務。",
    "geoLat": 25.1385,
    "geoLon": 121.554
  },
  {
    "id": "site_30",
    "code": "30",
    "name": "下竹林福德宮",
    "category": "民間信仰",
    "plusCode": "4GJW+7F",
    "district": "south",
    "districtName": "南區・花卉信仰與門戶",
    "x": 560,
    "y": 890,
    "radius": 40,
    "title": "30 下竹林福德宮",
    "description": "座落於仰德大道四段下竹林步道旁的石造古老土地公小廟，位於由台北市區進入陽明山的第一道門戶山階處，百年來默默守護往來仰德大道的登山健行者與歸鄉居民。",
    "geoLat": 25.13062,
    "geoLon": 121.54613
  }
];
